### ISSUE TITLE
Seperating the library from the client

### ISSUE THREAD

**Issue by int-72h** [Jan200101/OFQT#1]
It'd be neat if the actual interfacing code was seperate from the rest of the client code in the same way pytoast is seperate from rei/jam, in the case that alternate clients in C would want to be developed ~~definitely not trying to get this compiled in cc65~~.

**Comment by Jan200101** [comment]
the way the code is structured the core tvn code is seperated from the interfaces and projects leveraging tvn can load in the libary by import the main CMakeLists.txt and disabling BUILD_QT and BUILD_CLI.

**Comment by Jan200101** [comment]
I've created a little example project that shows how to load in libtvn
https://github.com/Jan200101/libtvn-example

note that libtvn was designed to always be linked directly as objects and is not available as a static or dynamic libary
